name: Mooses-Trinkets
version: '${project.version}'
main: me.plainoldmoose.trinkets.Trinkets
depend: [ eco ]
softdepend:
  - Vault
  - LPC
  - LuckPerms
api-version: '1.20'
commands:
  trinkets:
    description: "Open your trinkets"
    usage: "/trinkets"
    aliases: [ tk ]
    permission: trinkets.open
    permission-message: "You do not have permission to open your trinkets!"
permissions:
  trinkets.admin:
    default: op
  trinkets.open:
    default: op